import Head from 'next/head'
import movies from 'data/a24.json'
import Link from 'next/link'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <div>
        <h1>Movies</h1>
        <div>
        {
          movies.map((movie, i) => {
            return (
              <Link 
                href={{
                  pathname: '/info',
                  query: {
                    name : encodeURIComponent(movie.title),
                    cast : movie.Starring.replace(/[\[\]']+/g,''),
                    runtime : movie["Running time (int)"],
                    releaseDate : encodeURIComponent(movie["Release dates (datetime)"].replace(/^(\d{4})-\d{2}-\d{2}$/, '$1'))
                  }
                }}
                key={i}
              >
                <div>
                  <h1
                    onClick={() => {
                      console.log(movie["Release dates (datetime)"])
                      // findMovie(movie.title)
                    }}
                  >{movie.title}</h1>
                  <p>{movie.Starring.replace(/[\[\]']+/g,'')}</p>
                </div>
              </Link>
            )
          })
        }
        </div>
      </div>
    </main>
  </>
  )
}
