import Head from 'next/head'
import movies from 'data/a24.json'
import Link from 'next/link'
import Nav from '@/comps/nav'
import AccordionComp from '@/comps/accordion'


export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main
      className='h-screen md:overflow-y-hidden'
    >
    <Nav />
      <div
        className='w-screen h-screen grid grid-rows-2 md:grid-cols-2'
      >
        <div 
          className='w-full h-screen bg-blue-400'
        >

        </div>
        <div
          className='w-full h-screen md:overflow-y-scroll'
        >
        {
          movies &&
          movies.map((movie, i) => {
            return (
              <AccordionComp 
                title={movie.title} 
                cast={movie.Starring.replace(/[\[\]']+/g,'')} 
                index={i+1} 
                key={i}
                release={movie["Release dates (datetime)"].replace(/^(\d{4})-\d{2}-\d{2}$/, '$1')}
                movie={movie}
              />
            )
          })
        }

        </div>
      </div>
    </main>
  </>
  )
}
